language: node_js
node_js:
  - "10"
install:
  - npm install
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: bash pu.sh
    on:
      branch: master
      tags: false
  - provider: npm
    email: donaldaverill@gmail.com
    api_key:
      secure: uYsrMqxMD7wFT4V+35Wwy/l8FaGPDPIVOjangTlFzkjraRgSnACz2wcEt/Bjnl/XX+y0bf8juKdUYx8H+OczDYRo0OtIsSnbZ4Xbi11vMKVJGYTzD/3Z78BP7mP1bsDBhHJ/tM+kyxFLJAZegk23Q905LqKb98iy8DV1OyhJzY8Ro0W7/LU4ovats9f1dNTimyuFZRs/5SCKcJS7Rnmqti6l3OqbhBoiM4rWudZaz2+cE6/u560Dzmsb1Go13GYM2QZZaF2oyuo4IzVqvW0oNHN+O6BabX0oeVd7mpdM7mBW9wm3LzhEesRjXWU8IW5d/UC+7YuZ8YLY/igV0phC1NOvEV7kBN/OXDwSaYmB8RqgJh6LHRsezbKIEjNm+UFY7yJY5GkcbYnnubtmT4J+MysvSpuWQtEi/3L/60Jd2NllfiYPjjHiwty2W6Gz8gKAcmv3SxAsxNULK0wsuPio7ltrAkULZbbscmVl/gH9XG+inSqpb2Xpq3Aj/WGtEH/3XCNAd8iIxHVhr/4quO4uCXXHo7+7iIF7v1ayxGpBlPrljxyymLj2q0ZCpuhdMDeaFEgYQWvLjds05vhXe/BppSx1ns/o/a/ZfEe4ENLYATHuBvoG6cQqyyLRjKBv2kPQljD0/oVkumbE1Ai0uX0XD/hxnaq5j6AwcsvW9x0TFiU=
    on:
      branch: master
    tag: next
notifications:
  email:
    recipients:
      - donaldaverill@gmail.com
    on_success: change
    on_failure: always
