language: node_js
node_js:
  - "10"
install:
  - npm install
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: bash pu.sh
    on:
      branch: master
      tags: false
  - provider: npm
    email: donaldaverill@gmail.com
    api_key:
      # travis login --com
      # travis encrypt --com TOKEN
      secure: "eD8/jCtFUYv206R7xB80AYonqGv6CWazTm2yNuB8ll2DA54zaTnfeSX1tLcWC5iCvaKN+l401pTC7kIwPdcxWgV2BvEz8smpIp80lElUE54PkRIenb5MU9Cot2Jw8KAWyBVxFL5txcmLrIslg07uOwaN6uuNzJX3WLlXnA64NgqYLtO5ate+9OBzUiU/61GwE5sDIsmMzrKj8v2fyn+j9ATSmubA+eBphzraAhJpRqZFBqRRLix6pFMr9fkSzMfJtPD5gE69WOK5k91ak6DAUuLGUHKAXWb9jVQ8b9+hT6DcOtV15OYAFVyJ21R3TzTU9ax4cbShkJ3opFlx2ZzMaEJ4mOX6Ny4Q9gLa/6JkrIGj6cAaqnitB3pXMiqGpLznyc84UnRx1KhlbbL07Zy1MBQx7GEZWtcJtdVzT5CxlUiKHkEa8vlIBz4F9eI2WFf+BZUWRUfBG2fyDGFHHbztO03XxzfXTeR0Osf+lYR/FmfJlPGX00IiVACf9clcYK+q9GGhQKb2bOCeaQQ0V4A57YJfkQQQfFuiGcrKkCBcc7c1mOXXT+xfu+1xawvXwhCpyW8n6+OsSmrpz6QVGEnIKeiUa0DCSw0wmpw9Zb49HJOU3UcbpKsjc0UGvEkHwrpUXw1B7rTvEJblPZlqBKdn6DyXgEAJ/C7wbGdVALK7Mig="
    on:
      branch: master
notifications:
  email:
    recipients:
      - donaldaverill@gmail.com
    on_success: change
    on_failure: always
