language: node_js
node_js:
  - "10"
install:
  - npm install
script:
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: bash pu.sh
    on:
      branch: master
      tags: false
  - provider: npm
    email: donaldaverill@gmail.com
    api_key:
      secure: st1wGR2HiWrvinUmPBK2PBlrQFR8j0ukuP6M7MLTZruLEnsGAePowzHWhCZfNpujyr16KNPeHfHz2eEqSU3/atcZgWlsGQpecOsmQmD4P4QEmnKCBcbXkjJbAJPg2VddBC9V7ZpwgmC93DoGUEQVvIMO1NZZJOyNDFhN4vVxN99pRzFOu2HJZwsBVSo8Dxl70+TtdnKzJaA2BTSLcvGffPd9W0X7X557d2Zv4XZjtfGXLliQw4D9uqWtW49aqW7TmkUKcUiF+QDfjnskwo/EHR8POyXmBf9wmpdnbPZvgoDk+bxkCC+pDJAL6/WEL1Gb3lhrbkF3AKk0bUhwP1eHwxdOfnRr9ALQwEYXbHjCnTxnpwu3vsAZ0o9aFsZA7q7Ntuhw3rOPyVfBoI61H2p2GCQdtuPK5z2RywCijrZD38gtLfN2s2ennvpriqFI+hcQeq0CtBHQaCGY/rLA5WWO9AdlcEUTUeRnATbBnOidph7OE1n1VxUX8oC87FoneJlU6Kp222r4ki40qiU+6tGx2EH8/txnr97kOSILTwsFJ5wp6FQhJ0fWxPAP3qYRwQSiJLCg4WHR9+aRLp29gRJzt6jCzpy4ACJHASOT1xu9PMVNWC87HCgAG9A5InGeoGlQToJpH2EqgQxnF9nF4PcGZjQ0NehJ/fHZcY3IGdPyxx8=
    on:
      branch: master
    tag: next
notifications:
  email:
    recipients:
      - donaldaverill@gmail.com
    on_success: change
    on_failure: always
